name: Build Nuitka Wheels

on:
  push:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          CIBW_BEFORE_BUILD: "pip install numpy nuitka"
          CIBW_ENVIRONMENT: "NUITKA_NOCACHE=1"
          CIBW_BUILD_FRONTEND: "pip"
          # Correct package installation commands per OS/container:
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y gcc gcc-c++ python3-devel && 
            python -m pip install --upgrade pip setuptools wheel
          CIBW_BEFORE_ALL_MACOS: >
            brew install llvm &&
            python -m pip install --upgrade pip setuptools wheel
          CIBW_BEFORE_ALL_WINDOWS: >
            choco install llvm &&
            python -m pip install --upgrade pip setuptools wheel
          # Clearly specify architectures:
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "x86_64"
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Upload built wheels (clearly)
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
